# Use official Python base image
FROM python:3.10-slim
# Set environment vars
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
# Set working directory
WORKDIR /app
# Copy app code into container
COPY . /app
# Install dependencies
RUN pip install --no-cache-dir --upgrade pip && \
   pip install --no-cache-dir streamlit xgboost scikit-learn pandas
# Expose Streamlit port
EXPOSE 8501
# Start the app
CMD ["streamlit", "run", "app.py", "--server.port=8501", "--server.enableCORS=false"]